### ISSUE TITLE
#c20-293: Case sensivity in non-standard author names

### ISSUE THREAD

**Issue by Spriggana** [calibre2opds/calibre2opds#11]
For authors with uppercase letter in the middle of their name, that do not match the standard cases lika McSomething od MacOther there are problems with generated folder names.
For instance, folder for Jennifer McAndrews’ books is named  /Jennifer%20McAndrews/ while folder for Jeff VanderMeer’s books is named /Jeff%20Vandermeer/ 
This would not be a big problem if the html/xml catalogue pages would use the same foldr names, but they always use the proper names and link to /Jennifer%20McAndrews/ (folder exists) and /Jeff%20VanderMeer/ (folder does not exist)

**Comment by calibre2opds** [comment]
I think this is a problem where the case of the names in the Calibre database do not match those of the underlying folders/files.    Calibre2opds works of the Calibre database.  You get away with this on a system like Windows where the file system is case insensitive but it causes a problem when the web server is hosted on a case sensitive system.

I have been working on detecting this scenario so at least a warning can be flagged up.   Not sure if it can be corrected for though.

**Comment by Spriggana** [comment]
I just checked the calibre folders on a local database (Windows 7) – the folder for Jeff VanderMeer is capitalized correctly, as is the author's name in filenames. The opds catalogue (Linux system accessed via samba) spells Vandermeer like that both in forder name and filenames.
I just did a few experiments on my own.
1) tried to create folder "Jeff VanderMeer" within the opds catalogue from Windows – the system does not allow it claiming such name already exists (tested both from Windows GUI and command line)
2) tried to create folder "Jeff VanderMeer" on the linkux systen – it worked, and Samba saw both folders (did not try to work on those folders to not to confuse Windows more then necessary ;-))
3) manually copied files or folders from Calibre database onto the samba drive. every time the copied one had VanderMeer capitalized correctly, even when I used **all** lowercase spelling from the command line. Also, the autocomplete in command line always use the VanderMeer capitalization.
So it looks like all the available information on Windows system is correct. Could it be a strange java issue…?

**Comment by Spriggana** [comment]
I have just found a second example, and it is even stranger one. Aliette de Bodard’s name gets transformed to Aliette De Bodard, while Anders de la Motte gets through just fine… 8-)

**Comment by calibre2opds** [comment]
You need to check in Calibre itself exactly what the capitalisation of the author is set to for a particular book.    The catalog generation is using the capitalisation stored in the Calibre database which might be different to what is on disk.    In a purely Windows environment this mismatch is not immediately obvious as the file system is case insensitive.

However many web servers are hosted on a Linux system where case DOES matter so if the catalog is generated on Windows but then hosted elsewhere for access from the internet then you can get the URL’s failing to work.

Historically Calibre2opds has just checked for a files existence using a standard ‘exists’ type call.   This succeeds on Windows even when there is case mismatch as the Windows file system ignores case.   The URLs are then generated according to the value in the database.    I have recently found out a convenient manner of detecting the actual case of the file stored on a Windows system and am working on a patch that will:
- Write a warning to the log file that there is a case mismatch between the file system and the Calibre database.   This will help those who may later want to move the Calibre library to a system where filename case matters as unless these scenarios are corrected then Calibre can ‘lose track’ of such files.
- change the URL’s to match the actual case of the files that are found.   This should help those who already have such a mismatch and do not want to go through the effort of getting Calibre and the file system perfectly aligned.

**Comment by calibre2opds** [comment]
You need to look at a specific book to see what the settings are for that book.   You may see a discrepancy at that level.   The URL generated should match what you see at that level.

This is a problem that should only be significant if you have Calibre running on Windows and the web site on something else’s.   If you copied a library in this state to,Linux and then ran the Linux Calibre library maintenance I think you would find that lots of books come up missing because of this mismatch.     Hopefully the patch I am working on will correct for this mis-match and also give warnings about books that might be affected in case you decide to later move Calibre to another OS.   

I might also have to look into whether the Calibre library can be auto-corrected to match the Calibre database but I am reluctant to do that in case I messed something up.   At the moment Calibre2opds does not change any files/folders that belong to Calibre.

**Comment by calibre2opds** [comment]
I am not sure where Calibre2opds could be getting any folder/filename cases that does not match what is shown in Calibre!   In my experience the problem has always been when the underlying folders or filenames did not match what Calibre shows.   Once the underlying folders have the wrong case for any reason it stays wrong as Calibre does not detect it.   The only workaround I have found is to temporarily change the author name in Calibre (e.g. add an ‘x’ to the end) and then rename it back to the correct value.   This double rename step leaves you with the folder and filenames matching Calibre as far as case is concerned.

Note that working at the Samba level on Linux will not correct such a problem as Samba tries hard to mimic the case independence of Windows.   I am not sure what your setup actually is in terms of where the Calibre library is located and where the web server is running.   I mention this because if you have copied the library + catalog from a Windows system to a Linux system via Samba then it is possible you have got yourself into a state where the case of the folders/files on Linux is no longer the same as on the Windows system.     In such a case you need to delete the Linux copy of the catalog+library and then recopy from Windows to get the Linux case matching the Windows one.

**Comment by calibre2opds** [comment]
Fixing the URL’s to match the filename case is proving a little more challenging than I thought.   I now intend to look at going the other way and changing the case of filenames to match what is stored in the Calibre database.   Since this could potentially go wrong (although I will try and test it thoroughly to try and avoid that) I am going to introduce a new option on the Main tab for auto-correcting case sensitivity issues that the user will have to actively select (and label it Experimental in the help text until feedback is obtained on how successful it is).

In the meantime I have made rev 422 available for download which will write a warning to the log file for each mismatch found.   The end-of-run dialog also now gives a count of warnings written to the log file so you can see the scale of any problems.

**Comment by calibre2opds** [comment]
The option to auto-correct filename case mismatches is now implemented.   This is available in rev 423.

As a side-effect using this option will fix any case related issues in moving the Calibre library from a case insensitive system (e.g. Windows) to one where file name case matters (e.g. Linux).
