### ISSUE TITLE
Ordering all books by series does not work

### ISSUE THREAD

**Issue by Spriggana** [calibre2opds/calibre2opds#12]
Probably since upgrade to version 3.6 rev. 407 the option for ordering "all books" catalogue by series stopped working. I have tried turning it on and off regenerating the catalogue every time, and "all books" by author are sorted by title regardless of the setting.

**Comment by calibre2opds** [comment]
I will check this out.   I must admit I have the All Books option disabled in my own library as I find it not that useful with a large library.

**Comment by Spriggana** [comment]
Just to make sure – I m’m talking about the _all books by author X_ part, not _all books in whole library_.

**Comment by calibre2opds** [comment]
I will check - but I am reasonably certain that is by design!   The idea is that if you are interested in the Series for an author then you will have set the option to show the series in the author catalog, and can navigate directly to the series books from there.   If you have no idea what series a book belongs to then a pure alphabetical listing under the All Books section for the author is more useful.

The option in the GUI to sort “”All Books by series” is only meant to apply to the All Books part of the main catalog, not within an author.  That is one of the reasons it organised on the same line as turning the All Books part of the catalog on/off.   Maybe the help text associated with that setting should make this clearer?   The GUI option should probably also show as disabled if the option to generate the main All Books section has been turned off.

**Comment by Spriggana** [comment]
Anyway – it did worked differently in earlier versions. Could be by mistake… :-)

**Comment by calibre2opds** [comment]
It may have worked differently in earlier versions - as you say probably by mistake.     There has been a lot of tidying up of code internally and probably somewhere this changed.

If you can give a good Use Case where this would be desirable then I could look into making it an option.  The actual code to change the sorting is trivial - the effort is in adding it as an option to the GUI.

**Comment by Spriggana** [comment]
As I remember I used to download the books to Moon Reader from "all books by X" instead of series because of the filenames. When downloading from series catalogue the filename started with a volume number, and if I wanted to create a shortcut to a book on the main screen the name there also started with a number leaving even less space for the actual title. I stopped creating the shortcuts sometime ago, when it had become easier to navigate the downloaded book within Moon Reader, but by that time I had been pretty much used to using the "all books by X" catalogue and seeing the books grouped by series. No big problem, if now it works as it had been supposed to, I’ll get used to it too.
